---
title: Contextual Retrieval
---
flowchart LR
    subgraph Retrieve[Retrieval]
    F{Search For X Term} --> G[X Term Turned into Embeddings]
    G --> H[Run Embeddings Search]
    G --> I[Run BM25 Search on TF-IDF Encodings]

    H --> J[Rank Fusion + de-dupe + top_k]
    I --> J

    J --> K[Docs for AI Context]
    end

    subgraph Gen[Generate Context]
    A[Generate Corpus] --> B[Markdown Doc Set]
    B --> C[Generate Context Block For Chunk]
    C --> D[Create Embeddings from Text]
    D --> D1[Store in Vector DB]
    C --> E[Create TF-IDF Encodings of Doc]
    E --> E1[Store Encodings in ElasticSearch]
    style A fill:#666,stroke:#333,stroke-width:4px
    style B fill:#666,stroke:#333,stroke-width:4px
    style C fill:#666,stroke:#333,stroke-width:4px
    end
